# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
      - name: use Node.js 10.x
        uses: actions/setup-node@v1

      # Runs a set of commands using the runners shell
      - name: Installing...
        run: |
          npm install 
      - name: Building...
        run: |
          npm run build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy-to-server
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.SHHBQP_SSH_KEY }}
          ARGS: "-e -c -r --delete"
          SERVER_PORT: ${{ SHHBQP_SSH_PORT }}
          FOLDER: "./dist"
          SERVER_IP: ${{ secrets.SHHBQP_SSH_ADDR }}
          USERNAME: ${{ secrets.SHHBQP_SSH_USR }}
          SERVER_DESTINATION: ${{ secrets.SHHBQP_SSH_TARGET }}
      
    

